### ISSUE TITLE
Draft spec review: style sheet copying

### ISSUE THREAD

**Issue by domenic** [steimelchrome/steimelchrome.github.io#10]
The style sheet copying text currently says:

> the [CSS style sheet](https://drafts.csswg.org/cssom-1/#css-style-sheet)s applied the current [associated Document](https://html.spec.whatwg.org/multipage/window-object.html#concept-document-window) should be copied and applied to the target browsing context’s [associated Document](https://html.spec.whatwg.org/multipage/window-object.html#concept-document-window).

First, I suspect "should" is not intended here (i.e., the behavior is not optional).

Second, there often is more than one CSS style sheet applied to a document. There can be many, in fact: some from `<style>`, some from `<link>`, some from `adoptedStyleSheets`... Which ones do you want to copy? As per #6, you need to navigate to each of these collections in a precise manner, and gather up the appropriate objects to copy over.

Third, what exactly are the appropriate objects to copy over, and what does copying mean? Are you going to insert a `<style>` for each source `<style>`, a `<link>` for each source `<link>`, etc.? What if some of them failed to load? Are you going to copy over the text exactly, including e.g. syntax errors and exact whitespace, or will you instead copy over some serialization and then deserialize it? All of these things are observable.

**Comment by steimelchrome** [comment]
migrated to https://github.com/WICG/document-picture-in-picture/issues/12
