### ISSUE TITLE
Draft spec review: API surface indirection and verbosity seems excessive

### ISSUE THREAD

**Issue by domenic** [steimelchrome/steimelchrome.github.io#5]
- `navigator.documentPictureInPicture`: can this just be `documentPictureInPicture`? (I.e. a property of `Window`.) It doesn't seem to have anything to do with `navigator`.

- `documentPictureInPicture.session.window`: can this just be `documentPictureInPicture.window`? What is the session abstraction buying us?

- `documentPictureInPicture.onenterpictureinpicture`: can this just be `documentPictureInPicture.onenter`?

- `event.documentPictureInPictureSession`: can this just be `event.session`? I think from the fact that the event is firing on `documentPictureInPicture`, it's pretty clear what kind of session we're dealing with.

**Comment by steimelchrome** [comment]
I've done all of these except the first. I don't really have strong feelings about which is right, but I went with putting it on Navigator to match similar-ish APIs I know of (navigator.mediaSession, navigator.presentation, navigator.mediaCapabilities, etc). I don't actually know what makes something good to put on Navigator vs Window. Do you have any insight?

**Comment by domenic** [comment]
I think a lot of people cargo-cult stuff onto Navigator, but originally it was intended for stuff like `navigator.userAgent` that was about the browser... So I generally prefer not using it as a prefix.
