### ISSUE TITLE
Draft spec review: avoid monkeypatching/action at a distance

### ISSUE THREAD

**Issue by domenic** [steimelchrome/steimelchrome.github.io#8]
Your spec includes two normative monkeypatches (see [W3C TAG design principles](https://w3ctag.github.io/design-principles/#monkey-patching) and [Anne's blog](https://annevankesteren.nl/2014/02/monkey-patch) for more on why this is bad):

- https://steimelchrome.github.io/draft_spec.html#one-pip-window monkeypatches other parts of the spec, with a normative "must" requirement. Instead, that requirement needs to be incorporated (and made precise---what are "appropriate events"??) in the place where picture-in-picture statuses change.

- https://steimelchrome.github.io/draft_spec.html#relative-urls monkeypatches the entire web platform's URL resolution. This is quite bad! And probably not what you intended. I suspect instead you want to create the new browsing context / Window / Document with an overridden base URL of some sort.

**Comment by steimelchrome** [comment]
Migrated to https://github.com/WICG/document-picture-in-picture/issues/10
